In [5]:
import json
from pathlib import Path

import pandas as pd

In [6]:
results_dir = Path("./results")

# Basic Info on file_info.json

In [13]:
# Load the validation paired data (most manageable size)
path = Path("../PrimeVul_v0.1/file_info.json")

with open(path, "r") as f:
    data = json.load(f)

df = pd.DataFrame(data)

print("================================= file_info.json =============================")
print("--------------------------------- DataFrame info ---------------------------------")
print(df.info())
print(f"Samples: {len(df)}")


# Write head of file_info.json into file
with open(f"{results_dir}/file_info_head.json", "w") as f:
    json.dump(df.head().to_dict(), f, indent=4)

df.head()

================================= file_info.json =============================
--------------------------------- DataFrame info ---------------------------------
<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, file_name to end_line
Columns: 159694 entries, 337067086294432476558531070579523621153 to 339462409582323609876619479997559523135
dtypes: object(159694)
memory usage: 7.3+ MB
None
Samples: 6

,337067086294432476558531070579523621153,197963032555515457429901232523719816556,316363513618350025161684726236205110921,201049549109017217257267267643853566891,18151887717942448447675753037251831014,108448363166708106481706651605829401639,16170181608118934988978362082255880654,8624577151296783341485283445712813523,82775586910543808356902125173337611502,322047454318382561133365136181994780496,...,264222038452272834903874506167556918140,89795525620056718732182897563677394224,227054337348100081443730238937371479714,270558648427050529676746503291865575501,11217906215366786595720467912384536923,62747746497832992046621007241994402978,300223885952826828217115360495966209699,157778762757139198195544003006877135735,191536719324548282286244414856107770627,339462409582323609876619479997559523135
file_name,asn1write.c,asn1write.c,asn1write.c,asn1write.c,asn1write.c,asn1write.c,asn1write.c,asn1write.c,asn1write.c,asn1write.c,...,dwarf_form.c,dwarf_form.c,memory.c,pict.c,rle.c,sun.c,sun.c,sun.c,ares_parse_a_reply.c,ares_parse_a_reply.c
file_hash,77743259478449323467778529846528761559,77743259478449323467778529846528761559,77743259478449323467778529846528761559,77743259478449323467778529846528761559,77743259478449323467778529846528761559,77743259478449323467778529846528761559,77743259478449323467778529846528761559,77743259478449323467778529846528761559,77743259478449323467778529846528761559,77743259478449323467778529846528761559,...,223310352218560877749717840143149287287,228293279858083678183467583038909005245,107725265197795378275724473863360203805,203616907333475799469590016688058235293,190426794596482404925580596640849715320,28711367474383461954636738905406724279,28711367474383461954636738905406724279,28711367474383461954636738905406724279,20990464461145040008470659069666566182,202110915441919842050625018353616781489
project_file_path,library/asn1write.c,library/asn1write.c,library/asn1write.c,library/asn1write.c,library/asn1write.c,library/asn1write.c,library/asn1write.c,library/asn1write.c,library/asn1write.c,library/asn1write.c,...,src/lib/libdwarf/dwarf_form.c,src/lib/libdwarf/dwarf_form.c,MagickCore/memory.c,coders/pict.c,coders/rle.c,coders/sun.c,coders/sun.c,coders/sun.c,rutil/dns/ares/ares_parse_a_reply.c,rutil/dns/ares/ares_parse_a_reply.c
local_file_path,file_contents/mbedtls/777432594784493234677785...,file_contents/mbedtls/777432594784493234677785...,file_contents/mbedtls/777432594784493234677785...,file_contents/mbedtls/777432594784493234677785...,file_contents/mbedtls/777432594784493234677785...,file_contents/mbedtls/777432594784493234677785...,file_contents/mbedtls/777432594784493234677785...,file_contents/mbedtls/777432594784493234677785...,file_contents/mbedtls/777432594784493234677785...,file_contents/mbedtls/777432594784493234677785...,...,file_contents/libdwarf-code/223310352218560877...,file_contents/libdwarf-code/228293279858083678...,file_contents/ImageMagick/10772526519779537827...,file_contents/ImageMagick/20361690733347579946...,file_contents/ImageMagick/19042679459648240492...,file_contents/ImageMagick/28711367474383461954...,file_contents/ImageMagick/28711367474383461954...,file_contents/ImageMagick/28711367474383461954...,file_contents/resiprocate/20990464461145040008...,file_contents/resiprocate/20211091544191984205...
start_line,42,75,85,101,138,151,165,186,203,233,...,2035,676,576,805,127,212,634,703,34,34

In [14]:
# Transpose file_info
df_transposed = df.T
print("--------------------------------- Transposed DataFrame info ---------------------------------")
print(df_transposed.info())
print("A few samples")

# Write head into a file
with open(f"{results_dir}/file_info_t_head.json", "w") as f:
    json.dump(df_transposed.head().to_dict(), f, indent=4)

df_transposed.head()

--------------------------------- Transposed DataFrame info ---------------------------------
<class 'pandas.core.frame.DataFrame'>
Index: 159694 entries, 337067086294432476558531070579523621153 to 339462409582323609876619479997559523135
Data columns (total 6 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   file_name          159694 non-null  object
 1   file_hash          159694 non-null  object
 2   project_file_path  159694 non-null  object
 3   local_file_path    159694 non-null  object
 4   start_line         159694 non-null  object
 5   end_line           159694 non-null  object
dtypes: object(6)
memory usage: 12.6+ MB
None
A few samples

,file_name,file_hash,project_file_path,local_file_path,start_line,end_line
337067086294432476558531070579523621153,asn1write.c,77743259478449323467778529846528761559,library/asn1write.c,file_contents/mbedtls/777432594784493234677785...,42,73
197963032555515457429901232523719816556,asn1write.c,77743259478449323467778529846528761559,library/asn1write.c,file_contents/mbedtls/777432594784493234677785...,75,83
316363513618350025161684726236205110921,asn1write.c,77743259478449323467778529846528761559,library/asn1write.c,file_contents/mbedtls/777432594784493234677785...,85,98
201049549109017217257267267643853566891,asn1write.c,77743259478449323467778529846528761559,library/asn1write.c,file_contents/mbedtls/777432594784493234677785...,101,135
18151887717942448447675753037251831014,asn1write.c,77743259478449323467778529846528761559,library/asn1write.c,file_contents/mbedtls/777432594784493234677785...,138,149

# Explore training data

In [18]:
from pathlib import Path
import pandas as pd

# Explore training data
train_data_path = Path("../PrimeVul_v0.1/primevul_train.jsonl")
train_data = []
with open(train_data_path, "r") as f:
    for line in f:
        train_data.append(json.loads(line))

train_df = pd.DataFrame(train_data)
print("================================= primevul_train.jsonl =============================")
print("--------------------------------- Training DataFrame info ---------------------------------")
print(train_df.info())
print(f"Samples: {len(train_df)}")

# Write head into a file
with open(f"{results_dir}/primevul_train_head.json", "w") as f:
    json.dump(train_df.head().to_dict(), f, indent=4)

train_df.head()

================================= primevul_train.jsonl =============================
--------------------------------- Training DataFrame info ---------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175797 entries, 0 to 175796
Data columns (total 15 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   idx             175797 non-null  int64
 1   project         175797 non-null  object
 2   commit_id       175797 non-null  object
 3   project_url     175797 non-null  object
 4   commit_url      175797 non-null  object
 5   commit_message  175797 non-null  object
 6   target          175797 non-null  int64
 7   func            175797 non-null  object
 8   func_hash       175797 non-null  object
 9   file_name       175797 non-null  object
 10  file_hash       120537 non-null  float64
 11  cwe             175797 non-null  object
 12  cve             175797 non-null  object
 13  cve_desc        175797 non-null  object
 14  nvd_url         175797 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 20.1+ MB
None
Samples: 175797

,idx,project,commit_id,project_url,commit_url,commit_message,target,func,func_hash,file_name,file_hash,cwe,cve,cve_desc,nvd_url
0,0,openssl,ca989269a2876bae79393bd54c3e72d49975fc75,https://github.com/openssl/openssl,https://git.openssl.org/gitweb/?p=openssl.git;...,Use version in SSL_METHOD not SSL structure.\n...,1,long ssl_get_algorithm2(SSL *s)\n {\n ...,255087747659226932756944884868284698117,None,NaN,[CWE-310],CVE-2013-6449,The ssl_get_algorithm2 function in ssl/s3_lib....,https://nvd.nist.gov/vuln/detail/CVE-2013-6449
1,1,savannah,190cef6eed37d0e73a73c1e205eb31d45ab60a3c,https://git.savannah.gnu.org/gitweb/?p=gnutls,https://git.savannah.gnu.org/gitweb/?p=gnutls....,None,1,gnutls_session_get_data (gnutls_session_t sess...,266005388725654386397960628110885023158,None,NaN,[CWE-119],CVE-2011-4128,Buffer overflow in the gnutls_session_get_data...,https://nvd.nist.gov/vuln/detail/CVE-2011-4128
2,2,savannah,e82ef4545e9e98cbcb032f55d7c750b81e3a0450,https://git.savannah.gnu.org/gitweb/?p=gnutls,https://git.savannah.gnu.org/gitweb/?p=gnutls....,None,1,gnutls_session_get_data (gnutls_session_t sess...,162619476999663411812822607346255778028,None,NaN,[CWE-119],CVE-2011-4128,Buffer overflow in the gnutls_session_get_data...,https://nvd.nist.gov/vuln/detail/CVE-2011-4128
3,3,savannah,075d7556964f5a871a73c22ac4b69f5361295099,https://git.savannah.gnu.org/gitweb/?p=gnutls,https://git.savannah.gnu.org/cgit/wget.git/com...,None,1,"getftp (struct url *u, wgint passed_expected_b...",114753069609161113628525870463495041364,None,NaN,[CWE-200],CVE-2015-7665,Tails before 1.7 includes the wget program but...,https://nvd.nist.gov/vuln/detail/CVE-2015-7665
4,5,ghostscript,83d4dae44c71816c084a635550acc1a51529b881,http://git.ghostscript.com/?p=mupdf,http://git.ghostscript.com/?p=mupdf.git;a=comm...,None,1,void fz_init_cached_color_converter(fz_context...,183139468890710880163111516517773812467,colorspace.c,6.862522e+36,[CWE-20],CVE-2018-1000040,"In MuPDF 1.12.0 and earlier, multiple use of u...",https://nvd.nist.gov/vuln/detail/CVE-2018-1000040

## Explore paired

In [3]:
from pathlib import Path
import pandas as pd
from io import StringIO
import os
import json

# Explore primevul_train_paired.jsonl
data_path = Path("../PrimeVul_v0.1/primevul_train_paired.jsonl")
data = []

output = StringIO()
output_dir = Path("./results")
output_path = output_dir / "train_paired" / "info.md"


with open(data_path, "r") as f:
    for line in f:
        data.append(json.loads(line))

df_paired = pd.DataFrame(data)
print("================================= primevul_train_paired.jsonl =============================", file=output)
print("--------------------------------- DataFrame info ---------------------------------", file=output)
df_paired.info(buf=output)
print(f"Samples: {len(df_paired)}", file=output)


# Write info to file
os.makedirs(output_path.parent, exist_ok=True)
with open(output_path, "w") as f:
    f.write(output.getvalue())

# print
print(output.getvalue())

================================= primevul_train_paired.jsonl =============================
--------------------------------- DataFrame info ---------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7578 entries, 0 to 7577
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   idx             7578 non-null   int64
 1   project         7578 non-null   object
 2   commit_id       7578 non-null   object
 3   project_url     7578 non-null   object
 4   commit_url      7578 non-null   object
 5   commit_message  7578 non-null   object
 6   target          7578 non-null   int64
 7   func            7578 non-null   object
 8   func_hash       7578 non-null   object
 9   file_name       7578 non-null   object
 10  file_hash       4873 non-null   float64
 11  cwe             7578 non-null   object
 12  cve             7578 non-null   object
 13  cve_desc        7578 non-null   object
 14  nvd_url         7578 non-null   object
dtypes: float64(1), int64(2), object(12)
memory usage: 888.2+ KB
Samples: 7578

In [5]:
# Unique projects and CVEs

from io import StringIO

output = StringIO()
output_file = output_dir / "train_paired" / "info.md"

# Print and store stats
print("------------------------------------- Stats ----------------------------------------", file=output)
print("Total samples: ", len(df_paired), file=output)
print(f"Unique cve_ids = {df_paired['cve'].nunique()} ({df_paired['cve'].nunique()/len(df_paired)*100:.2f}%)", file=output)
print(f"Unique projects = {df_paired['project_url'].nunique()} ({df_paired['project_url'].nunique()/len(df_paired)*100:.2f}%)", file=output)

with open(output_file, "a" if output_file.exists() else "w") as f:
    f.write(output.getvalue())

print(output.getvalue())

------------------------------------- Stats ----------------------------------------
Total samples:  7578
Unique cve_ids = 3266 (43.10%)
Unique projects = 545 (7.19%)

In [7]:
# Top 10 projects by number of samples

output = StringIO()
output_path = output_dir / "train_paired" / "info.md"

# Top 10 projects by number of samples
top_projects = df_paired["project_url"].value_counts(sort=True).head(10)

print("--------------------------------- Top 10 Projects ---------------------------------", file=output)
for project, count in top_projects.items():
    print(f"{project}: {count} samples", file=output)

with open(output_path, "a") as f:
    f.write(output.getvalue())

print(output.getvalue())

--------------------------------- Top 10 Projects ---------------------------------
https://github.com/torvalds/linux: 1519 samples
https://github.com/ImageMagick/ImageMagick: 478 samples
https://github.com/chromium/chromium: 468 samples
None: 251 samples
https://github.com/bonzini/qemu: 236 samples
https://github.com/openssl/openssl: 192 samples
https://github.com/php/php-src: 186 samples
http://git.kernel.org/?p=linux/kernel/git/torvalds/linux-2.6: 149 samples
https://github.com/FFmpeg/FFmpeg: 132 samples
https://github.com/the-tcpdump-group/tcpdump: 124 samples

In [13]:
# Check whether number of projects equals number of unique URLs


num_projects = df_paired['project'].nunique()
num_unique_urls = df_paired['project_url'].nunique()
print(f"Number of unique projects: {num_projects}")
print(f"Number of unique project URLs: {num_unique_urls}")

print(num_projects == num_unique_urls)

Number of unique projects: 545
Number of unique project URLs: 545
True

In [23]:
# Distribution of samples per project
import matplotlib.pyplot as plt

output = StringIO()
output_path = output_dir / "train_paired" / "info.md"

# Convert 'project' into categorical for better memory usage
df_paired['project'] = df_paired['project'].astype('category')

# Plot distribution of top 20 projects (Project names on x-axis, number of samples on y-axis). Make figure wider for readability
plt.figure(figsize=(20, 6))
project_counts = df_paired['project'].value_counts().sort_values(ascending=False).head(20)
project_counts.plot(kind='bar')
plt.title('Distribution of Samples per Project')
plt.xlabel('Project')
plt.ylabel('Number of Samples')
plt.tight_layout()
plt_path = output_dir / "train_paired" / "samples_per_project.png"
plt.savefig(plt_path)
plt.close()

# Embed the plot in the markdown file
print("--------------------------------- Distribution of Samples per Project ---------------------------------", file=output)
print(f"![Samples per Project]({plt_path.name})", file=output)

with open(output_path, "a") as f:
    f.write(output.getvalue())

In [25]:
# Distribution of samples per CVE
import matplotlib.pyplot as plt

output = StringIO()
output_path = output_dir / "train_paired" / "info.md"

# Convert 'cve' into categorical for better memory usage
df_paired['cve'] = df_paired['cve'].astype('category')

# Plot distribution of top 20 CVEs (CVE IDs on x-axis, number of samples on y-axis). Make figure wider for readability
plt.figure(figsize=(20, 6))
cve_counts = df_paired['cve'].value_counts().sort_values(ascending=False).head(20)
cve_counts.plot(kind='bar')
plt.title('Distribution of Samples per CVE')
plt.xlabel('CVE')
plt.ylabel('Number of Samples')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt_path = output_dir / "train_paired" / "samples_per_cve.png"
plt.savefig(plt_path)
plt.close()

# Embed the plot in the markdown file
print("--------------------------------- Distribution of Samples per CVE ---------------------------------", file=output)
print(f"![Samples per CVE]({plt_path.name})", file=output)

with open(output_path, "a") as f:
    f.write(output.getvalue())

# Comprehensive Data Analysis

Performing detailed exploration for research planning

In [26]:
# Initialize report file
import os
from io import StringIO
from datetime import datetime

report_path = output_dir / "train_paired" / "llm_generated_report.md"

# Create initial report with header
with open(report_path, "w") as f:
    f.write(f"# PrimeVul Dataset Analysis Report\n\n")
    f.write(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
    f.write(f"**Dataset:** primevul_train_paired.jsonl\n\n")
    f.write(f"---\n\n")

print(f"Report initialized at: {report_path}")

Report initialized at: results/train_paired/llm_generated_report.md

## 1. Target Distribution Analysis

Verify that vulnerable and patched samples are balanced

In [27]:
# Target distribution analysis
target_counts = df_paired['target'].value_counts().sort_index()
total_samples = len(df_paired)

output = StringIO()
output.write("## 1. Target Distribution Analysis\n\n")
output.write("### Overview\n")
output.write(f"- **Total samples:** {total_samples}\n")
output.write(f"- **Vulnerable (target=1):** {target_counts.get(1, 0)} ({target_counts.get(1, 0)/total_samples*100:.2f}%)\n")
output.write(f"- **Patched (target=0):** {target_counts.get(0, 0)} ({target_counts.get(0, 0)/total_samples*100:.2f}%)\n\n")

# Check balance
balance_ratio = target_counts.get(1, 0) / target_counts.get(0, 0) if target_counts.get(0, 0) > 0 else 0
output.write(f"### Balance Ratio\n")
output.write(f"- **Vulnerable:Patched ratio:** {balance_ratio:.3f}\n")
if abs(balance_ratio - 1.0) < 0.1:
    output.write(f"- **Status:** ✅ Well-balanced (within 10% of 1:1)\n\n")
elif abs(balance_ratio - 1.0) < 0.3:
    output.write(f"- **Status:** ⚠️ Moderately imbalanced\n\n")
else:
    output.write(f"- **Status:** ❌ Highly imbalanced - investigate pairing logic\n\n")

# Visualization
plt.figure(figsize=(8, 6))
target_counts.plot(kind='bar', color=['#2ecc71', '#e74c3c'])
plt.title('Distribution of Vulnerable vs Patched Samples')
plt.xlabel('Target (0=Patched, 1=Vulnerable)')
plt.ylabel('Count')
plt.xticks([0, 1], ['Patched (0)', 'Vulnerable (1)'], rotation=0)
plt.tight_layout()
target_plot_path = output_dir / "train_paired" / "target_distribution.png"
plt.savefig(target_plot_path)
plt.close()

output.write(f"![Target Distribution]({target_plot_path.name})\n\n")

# Write to report
with open(report_path, "a") as f:
    f.write(output.getvalue())

print(output.getvalue())

## 1. Target Distribution Analysis

### Overview
- **Total samples:** 7578
- **Vulnerable (target=1):** 3789 (50.00%)
- **Patched (target=0):** 3789 (50.00%)

### Balance Ratio
- **Vulnerable:Patched ratio:** 1.000
- **Status:** ✅ Well-balanced (within 10% of 1:1)

![Target Distribution](target_distribution.png)

## 2. Pairing Validation

Check if consecutive rows form proper vulnerable/patched pairs

In [29]:
# Pairing validation - check if rows form proper pairs
output = StringIO()
output.write("## 2. Pairing Validation\n\n")

# Group by CVE and check pairing
cve_groups = df_paired.groupby('cve')

# Statistics
cves_with_both = 0
cves_only_vuln = 0
cves_only_patch = 0
cves_with_multiple = 0
perfect_pairs = 0

pairing_details = []

for cve, group in cve_groups:
    vuln_count = (group['target'] == 1).sum()
    patch_count = (group['target'] == 0).sum()
    
    if vuln_count > 0 and patch_count > 0:
        cves_with_both += 1
        if vuln_count == 1 and patch_count == 1:
            perfect_pairs += 1
        elif vuln_count > 1 or patch_count > 1:
            cves_with_multiple += 1
            pairing_details.append({
                'cve': cve,
                'vuln_count': vuln_count,
                'patch_count': patch_count,
                'total': len(group)
            })
    elif vuln_count > 0:
        cves_only_vuln += 1
    elif patch_count > 0:
        cves_only_patch += 1

total_cves = len(cve_groups)

output.write(f"### Pairing Statistics\n")
output.write(f"- **Total CVEs:** {total_cves}\n")
output.write(f"- **Perfect pairs (1 vuln + 1 patch):** {perfect_pairs} ({perfect_pairs/total_cves*100:.2f}%)\n")
output.write(f"- **CVEs with multiple versions:** {cves_with_multiple} ({cves_with_multiple/total_cves*100:.2f}%)\n")
output.write(f"- **CVEs with only vulnerable code:** {cves_only_vuln} ({cves_only_vuln/total_cves*100:.2f}%)\n")
output.write(f"- **CVEs with only patched code:** {cves_only_patch} ({cves_only_patch/total_cves*100:.2f}%)\n\n")

if cves_only_vuln > 0 or cves_only_patch > 0:
    output.write(f"⚠️ **Warning:** {cves_only_vuln + cves_only_patch} CVEs have incomplete pairs!\n\n")
else:
    output.write(f"✅ **All CVEs have both vulnerable and patched versions**\n\n")

# Show examples of CVEs with multiple versions
if pairing_details:
    output.write(f"### CVEs with Multiple Versions (Top 10)\n\n")
    pairing_df = pd.DataFrame(pairing_details).sort_values('total', ascending=False).head(10)
    output.write(pairing_df.to_markdown(index=False))
    output.write("\n\n")

# Check consecutive pairing pattern
consecutive_pairs = 0
for i in range(0, len(df_paired)-1, 2):
    if i+1 < len(df_paired):
        row1 = df_paired.iloc[i]
        row2 = df_paired.iloc[i+1]
        if (row1['cve'] == row2['cve'] and 
            row1['target'] != row2['target']):
            consecutive_pairs += 1

expected_consecutive = total_samples // 2
output.write(f"### Consecutive Pairing Pattern\n")
output.write(f"- **Consecutive pairs found:** {consecutive_pairs}\n")
output.write(f"- **Expected (total/2):** {expected_consecutive}\n")
output.write(f"- **Match rate:** {consecutive_pairs/expected_consecutive*100:.2f}%\n\n")

if consecutive_pairs / expected_consecutive > 0.9:
    output.write("✅ **Dataset follows consecutive pairing pattern**\n\n")
else:
    output.write("⚠️ **Dataset does NOT follow strict consecutive pairing**\n\n")

# Write to report
with open(report_path, "a") as f:
    f.write(output.getvalue())

print(output.getvalue())

/var/folders/g0/yxqzhyv91b7gnrp3xrhst1h40000gn/T/ipykernel_14888/2044644033.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  cve_groups = df_paired.groupby('cve')

## 2. Pairing Validation

### Pairing Statistics
- **Total CVEs:** 3266
- **Perfect pairs (1 vuln + 1 patch):** 2883 (88.27%)
- **CVEs with multiple versions:** 373 (11.42%)
- **CVEs with only vulnerable code:** 8 (0.24%)
- **CVEs with only patched code:** 2 (0.06%)

⚠️ **Warning:** 10 CVEs have incomplete pairs!

### CVEs with Multiple Versions (Top 10)

| cve            |   vuln_count |   patch_count |   total |
|:---------------|-------------:|--------------:|--------:|
| CVE-2005-4881  |           19 |            19 |      38 |
| CVE-2019-19532 |           14 |            14 |      28 |
| CVE-2018-8799  |           10 |            10 |      20 |
| CVE-2013-6825  |            8 |             8 |      16 |
| CVE-2019-19275 |            8 |             8 |      16 |
| CVE-2013-0169  |            7 |             7 |      14 |
| CVE-2014-0143  |            7 |             7 |      14 |
| CVE-2018-16643 |            7 |             7 |      14 |
| CVE-2020-8265  |            7 |             7 |      14 |
| CVE-2014-3184  |            6 |             6 |      12 |

### Consecutive Pairing Pattern
- **Consecutive pairs found:** 3772
- **Expected (total/2):** 3789
- **Match rate:** 99.55%

✅ **Dataset follows consecutive pairing pattern**

## 3. CWE Distribution Analysis

Analyze vulnerability types in the dataset

In [30]:
# CWE Distribution Analysis
import ast

output = StringIO()
output.write("## 3. CWE Distribution Analysis\n\n")

# Parse CWE field (it's a list stored as string)
all_cwes = []
multi_cwe_count = 0

for cwe_val in df_paired['cwe']:
    if isinstance(cwe_val, str):
        try:
            cwe_list = ast.literal_eval(cwe_val)
            if isinstance(cwe_list, list):
                all_cwes.extend(cwe_list)
                if len(cwe_list) > 1:
                    multi_cwe_count += 1
            else:
                all_cwes.append(cwe_list)
        except:
            all_cwes.append(cwe_val)
    elif isinstance(cwe_val, list):
        all_cwes.extend(cwe_val)
        if len(cwe_val) > 1:
            multi_cwe_count += 1

cwe_counts = pd.Series(all_cwes).value_counts()

output.write(f"### Overview\n")
output.write(f"- **Total CWE tags:** {len(all_cwes)}\n")
output.write(f"- **Unique CWE types:** {len(cwe_counts)}\n")
output.write(f"- **Samples with multiple CWEs:** {multi_cwe_count} ({multi_cwe_count/total_samples*100:.2f}%)\n")
output.write(f"- **Avg CWEs per sample:** {len(all_cwes)/total_samples:.2f}\n\n")

# Top CWE categories
output.write(f"### Top 20 CWE Categories\n\n")
top_cwes = cwe_counts.head(20)
cwe_df = pd.DataFrame({
    'CWE': top_cwes.index,
    'Count': top_cwes.values,
    'Percentage': (top_cwes.values / len(all_cwes) * 100).round(2)
})
output.write(cwe_df.to_markdown(index=False))
output.write("\n\n")

# Visualization
plt.figure(figsize=(14, 8))
top_cwes.head(15).plot(kind='barh', color='#3498db')
plt.title('Top 15 CWE Categories')
plt.xlabel('Number of Samples')
plt.ylabel('CWE')
plt.gca().invert_yaxis()
plt.tight_layout()
cwe_plot_path = output_dir / "train_paired" / "cwe_distribution.png"
plt.savefig(cwe_plot_path)
plt.close()

output.write(f"![CWE Distribution]({cwe_plot_path.name})\n\n")

# CWE category mapping (common ones)
cwe_categories = {
    'CWE-119': 'Buffer Overflow',
    'CWE-120': 'Buffer Copy without Checking Size',
    'CWE-125': 'Out-of-bounds Read',
    'CWE-787': 'Out-of-bounds Write',
    'CWE-416': 'Use After Free',
    'CWE-476': 'NULL Pointer Dereference',
    'CWE-190': 'Integer Overflow',
    'CWE-189': 'Numeric Errors',
    'CWE-200': 'Information Exposure',
    'CWE-20': 'Improper Input Validation',
    'CWE-79': 'Cross-site Scripting (XSS)',
    'CWE-89': 'SQL Injection',
    'CWE-264': 'Permissions/Privileges',
    'CWE-310': 'Cryptographic Issues',
    'CWE-362': 'Race Condition',
}

output.write(f"### Common CWE Categories Found\n\n")
for cwe, desc in cwe_categories.items():
    if cwe in cwe_counts.index:
        count = cwe_counts[cwe]
        output.write(f"- **{cwe}** ({desc}): {count} samples\n")
output.write("\n")

# Write to report
with open(report_path, "a") as f:
    f.write(output.getvalue())

print(output.getvalue())

## 3. CWE Distribution Analysis

### Overview
- **Total CWE tags:** 7578
- **Unique CWE types:** 112
- **Samples with multiple CWEs:** 0 (0.00%)
- **Avg CWEs per sample:** 1.00

### Top 20 CWE Categories

| CWE     |   Count |   Percentage |
|:--------|--------:|-------------:|
| CWE-119 |    1041 |        13.74 |
| CWE-125 |     790 |        10.42 |
| CWE-20  |     697 |         9.2  |
| CWE-787 |     514 |         6.78 |
| CWE-476 |     437 |         5.77 |
| CWE-200 |     420 |         5.54 |
| CWE-416 |     352 |         4.65 |
| CWE-399 |     297 |         3.92 |
| CWE-264 |     282 |         3.72 |
| CWE-190 |     279 |         3.68 |
| CWE-703 |     256 |         3.38 |
| CWE-189 |     245 |         3.23 |
| CWE-401 |     158 |         2.08 |
| CWE-772 |     143 |         1.89 |
| CWE-362 |     128 |         1.69 |
| CWE-369 |     116 |         1.53 |
| CWE-310 |     104 |         1.37 |
| CWE-284 |     100 |         1.32 |
| CWE-415 |      98 |         1.29 |
| CWE-835 |      91 |         1.2  |

![CWE Distribution](cwe_distribution.png)

### Common CWE Categories Found

- **CWE-119** (Buffer Overflow): 1041 samples
- **CWE-120** (Buffer Copy without Checking Size): 70 samples
- **CWE-125** (Out-of-bounds Read): 790 samples
- **CWE-787** (Out-of-bounds Write): 514 samples
- **CWE-416** (Use After Free): 352 samples
- **CWE-476** (NULL Pointer Dereference): 437 samples
- **CWE-190** (Integer Overflow): 279 samples
- **CWE-189** (Numeric Errors): 245 samples
- **CWE-200** (Information Exposure): 420 samples
- **CWE-20** (Improper Input Validation): 697 samples
- **CWE-79** (Cross-site Scripting (XSS)): 32 samples
- **CWE-89** (SQL Injection): 8 samples
- **CWE-264** (Permissions/Privileges): 282 samples
- **CWE-310** (Cryptographic Issues): 104 samples
- **CWE-362** (Race Condition): 128 samples

## 4. Code Length Analysis

Compare function sizes between vulnerable and patched versions

In [ ]:
# Code Length Analysis
output = StringIO()
output.write("## 4. Code Length Analysis\n\n")

# Calculate LOC for each function
df_paired['loc'] = df_paired['func'].apply(lambda x: len([l for l in str(x).split('\n') if l.strip()]))

# Separate by target
vuln_loc = df_paired[df_paired['target'] == 1]['loc']
patch_loc = df_paired[df_paired['target'] == 0]['loc']

output.write(f"### Lines of Code Statistics\n\n")
output.write(f"**Vulnerable Functions:**\n")
output.write(f"- Mean: {vuln_loc.mean():.2f} lines\n")
output.write(f"- Median: {vuln_loc.median():.2f} lines\n")
output.write(f"- Std Dev: {vuln_loc.std():.2f}\n")
output.write(f"- Min: {vuln_loc.min()} lines\n")
output.write(f"- Max: {vuln_loc.max()} lines\n\n")

output.write(f"**Patched Functions:**\n")
output.write(f"- Mean: {patch_loc.mean():.2f} lines\n")
output.write(f"- Median: {patch_loc.median():.2f} lines\n")
output.write(f"- Std Dev: {patch_loc.std():.2f}\n")
output.write(f"- Min: {patch_loc.min()} lines\n")
output.write(f"- Max: {patch_loc.max()} lines\n\n")

# Calculate difference for paired samples
# Group by CVE and calculate LOC delta
cve_deltas = []
for cve, group in df_paired.groupby('cve'):
    vuln = group[group['target'] == 1]
    patch = group[group['target'] == 0]
    if len(vuln) > 0 and len(patch) > 0:
        # Take first of each if multiple
        delta = patch.iloc[0]['loc'] - vuln.iloc[0]['loc']
        cve_deltas.append(delta)

if cve_deltas:
    cve_deltas_series = pd.Series(cve_deltas)
    output.write(f"### LOC Delta (Patched - Vulnerable)\n\n")
    output.write(f"- **Mean delta:** {cve_deltas_series.mean():.2f} lines\n")
    output.write(f"- **Median delta:** {cve_deltas_series.median():.2f} lines\n")
    output.write(f"- **Patches that add code:** {(cve_deltas_series > 0).sum()} ({(cve_deltas_series > 0).sum()/len(cve_deltas)*100:.2f}%)\n")
    output.write(f"- **Patches that remove code:** {(cve_deltas_series < 0).sum()} ({(cve_deltas_series < 0).sum()/len(cve_deltas)*100:.2f}%)\n")
    output.write(f"- **Patches with same LOC:** {(cve_deltas_series == 0).sum()} ({(cve_deltas_series == 0).sum()/len(cve_deltas)*100:.2f}%)\n\n")

# Visualization - LOC distribution
fig, axes = plt.subplots(1, 2, figsize=(20, 8))  # Larger figure

# Use kernel density estimation for smoother comparison
vuln_loc.plot.kde(ax=axes[0], color='#e74c3c', linewidth=2, label='Vulnerable')
patch_loc.plot.kde(ax=axes[0], color='#2ecc71', linewidth=2, label='Patched')
axes[0].set_xlabel('Lines of Code')
axes[0].set_ylabel('Density')
axes[0].set_title('LOC Distribution: Vulnerable vs Patched')
axes[0].legend()
axes[0].set_xlim(0, 200)

# Delta histogram
if cve_deltas:
    axes[1].hist(cve_deltas_series, bins=50, color='#3498db', alpha=0.7)
    axes[1].axvline(0, color='red', linestyle='--', linewidth=2, label='No change')
    axes[1].set_xlabel('LOC Delta (Patched - Vulnerable)')
    axes[1].set_ylabel('Frequency')
    axes[1].set_title('Distribution of LOC Changes')
    axes[1].legend()
    axes[1].set_xlim(-50, 50)  # Focus on main distribution

plt.tight_layout()
loc_plot_path = output_dir / "train_paired" / "loc_analysis.png"
plt.savefig(loc_plot_path)
plt.close()

output.write(f"![LOC Analysis]({loc_plot_path.name})\n\n")

# Write to report
with open(report_path, "a") as f:
    f.write(output.getvalue())

print(output.getvalue())

/var/folders/g0/yxqzhyv91b7gnrp3xrhst1h40000gn/T/ipykernel_14888/3249356334.py:30: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for cve, group in df_paired.groupby('cve'):

## 4. Code Length Analysis

### Lines of Code Statistics

**Vulnerable Functions:**
- Mean: 152.55 lines
- Median: 63.00 lines
- Std Dev: 481.64
- Min: 2 lines
- Max: 23899 lines

**Patched Functions:**
- Mean: 155.60 lines
- Median: 67.00 lines
- Std Dev: 483.23
- Min: 1 lines
- Max: 24007 lines

### LOC Delta (Patched - Vulnerable)

- **Mean delta:** 3.13 lines
- **Median delta:** 2.00 lines
- **Patches that add code:** 2155 (66.19%)
- **Patches that remove code:** 329 (10.10%)
- **Patches with same LOC:** 772 (23.71%)

![LOC Analysis](loc_analysis.png)

## 5. CWE by Project Analysis

Identify project-specific vulnerability patterns

In [33]:
# CWE by Project Analysis
output = StringIO()
output.write("## 5. CWE by Project Analysis\n\n")

# Get top projects
top_projects_list = df_paired['project'].value_counts().head(10).index.tolist()

# Extract primary CWE for each sample
def get_primary_cwe(cwe_val):
    if isinstance(cwe_val, str):
        try:
            cwe_list = ast.literal_eval(cwe_val)
            if isinstance(cwe_list, list) and len(cwe_list) > 0:
                return cwe_list[0]
            return cwe_list
        except:
            return cwe_val
    elif isinstance(cwe_val, list) and len(cwe_val) > 0:
        return cwe_val[0]
    return cwe_val

df_paired['primary_cwe'] = df_paired['cwe'].apply(get_primary_cwe)

# Create crosstab for top projects and top CWEs
top_cwes_list = df_paired['primary_cwe'].value_counts().head(10).index.tolist()

# Filter data
df_filtered = df_paired[
    (df_paired['project'].isin(top_projects_list)) &
    (df_paired['primary_cwe'].isin(top_cwes_list))
]

# Create crosstab
crosstab = pd.crosstab(df_filtered['project'], df_filtered['primary_cwe'])

output.write(f"### Top 10 Projects vs Top 10 CWEs\n\n")
output.write("Crosstab showing vulnerability type distribution across major projects:\n\n")
output.write(crosstab.to_markdown())
output.write("\n\n")

# Find project-CWE associations
project_cwe_analysis = []
for project in top_projects_list:
    project_data = df_paired[df_paired['project'] == project]
    if len(project_data) > 0:
        cwe_dist = project_data['primary_cwe'].value_counts().head(3)
        top_cwe = cwe_dist.index[0] if len(cwe_dist) > 0 else 'N/A'
        top_cwe_pct = (cwe_dist.values[0] / len(project_data) * 100) if len(cwe_dist) > 0 else 0
        
        project_cwe_analysis.append({
            'Project': project,
            'Total_Samples': len(project_data),
            'Top_CWE': top_cwe,
            'Top_CWE_Count': cwe_dist.values[0] if len(cwe_dist) > 0 else 0,
            'Top_CWE_Pct': f"{top_cwe_pct:.1f}%"
        })

output.write(f"### Dominant CWE per Project\n\n")
project_cwe_df = pd.DataFrame(project_cwe_analysis)
output.write(project_cwe_df.to_markdown(index=False))
output.write("\n\n")

# Heatmap visualization
plt.figure(figsize=(14, 10))
import seaborn as sns
sns.heatmap(crosstab, annot=True, fmt='d', cmap='YlOrRd', cbar_kws={'label': 'Sample Count'})
plt.title('Vulnerability Types (CWE) by Project')
plt.xlabel('CWE Category')
plt.ylabel('Project')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
heatmap_path = output_dir / "train_paired" / "cwe_by_project_heatmap.png"
plt.savefig(heatmap_path)
plt.close()

output.write(f"![CWE by Project Heatmap]({heatmap_path.name})\n\n")

# Write to report
with open(report_path, "a") as f:
    f.write(output.getvalue())

print(output.getvalue())

## 5. CWE by Project Analysis

### Top 10 Projects vs Top 10 CWEs

Crosstab showing vulnerability type distribution across major projects:

| project     |   CWE-119 |   CWE-125 |   CWE-190 |   CWE-20 |   CWE-200 |   CWE-264 |   CWE-399 |   CWE-416 |   CWE-476 |   CWE-787 |
|:------------|----------:|----------:|----------:|---------:|----------:|----------:|----------:|----------:|----------:|----------:|
| Android     |        65 |        12 |         6 |       24 |        38 |        52 |         2 |         0 |         2 |         4 |
| Chrome      |        76 |         8 |        10 |      108 |        24 |        34 |        64 |        34 |         0 |         4 |
| FFmpeg      |        34 |        18 |         0 |       10 |         2 |         0 |         6 |         2 |        18 |        12 |
| ImageMagick |        50 |        54 |        34 |       38 |         8 |         0 |        19 |        22 |        20 |        21 |
| linux       |       170 |        54 |        21 |      128 |       125 |        84 |        72 |       159 |        91 |        79 |
| linux-2.6   |        12 |         0 |         6 |       10 |        57 |        16 |        14 |         0 |         6 |         0 |
| openssl     |        16 |        14 |         2 |        9 |        14 |         0 |        13 |         0 |        20 |         8 |
| php-src     |        42 |        26 |        10 |       16 |         6 |         6 |         4 |        10 |        10 |        10 |
| qemu        |        38 |        14 |        22 |       32 |         6 |         4 |        17 |         2 |         6 |        22 |
| tcpdump     |         2 |       110 |         0 |        2 |         0 |         0 |         0 |         0 |         0 |         0 |

### Dominant CWE per Project

| Project     |   Total_Samples | Top_CWE   |   Top_CWE_Count | Top_CWE_Pct   |
|:------------|----------------:|:----------|----------------:|:--------------|
| linux       |            1519 | CWE-119   |             170 | 11.2%         |
| ImageMagick |             478 | CWE-772   |              79 | 16.5%         |
| Chrome      |             468 | CWE-20    |             108 | 23.1%         |
| Android     |             251 | CWE-119   |              65 | 25.9%         |
| qemu        |             236 | CWE-119   |              38 | 16.1%         |
| openssl     |             192 | CWE-310   |              42 | 21.9%         |
| php-src     |             186 | CWE-119   |              42 | 22.6%         |
| linux-2.6   |             149 | CWE-200   |              57 | 38.3%         |
| FFmpeg      |             132 | CWE-119   |              34 | 25.8%         |
| tcpdump     |             124 | CWE-125   |             110 | 88.7%         |

![CWE by Project Heatmap](cwe_by_project_heatmap.png)

## 6. Code Pattern Analysis

Search for common vulnerability and fix patterns

In [34]:
# Code Pattern Analysis
import re

output = StringIO()
output.write("## 6. Code Pattern Analysis\n\n")

# Define patterns to search for
vuln_patterns = {
    'unsafe_strcpy': r'\bstrcpy\s*\(',
    'unsafe_strcat': r'\bstrcat\s*\(',
    'unsafe_sprintf': r'\bsprintf\s*\(',
    'unsafe_gets': r'\bgets\s*\(',
    'malloc_call': r'\b(malloc|calloc|realloc)\s*\(',
    'free_call': r'\bfree\s*\(',
    'memcpy_call': r'\bmemcpy\s*\(',
    'pointer_deref': r'->',
    'array_access': r'\[.*\]',
}

patch_patterns = {
    'safe_strncpy': r'\bstrncpy\s*\(',
    'safe_strncat': r'\bstrncat\s*\(',
    'safe_snprintf': r'\bsnprintf\s*\(',
    'null_check': r'if\s*\([^)]*!=\s*NULL\)',
    'size_check': r'if\s*\([^)]*(<|>|<=|>=)[^)]*\)',
    'bounds_check': r'if\s*\([^)]*(size|len|length|count)[^)]*\)',
    'return_check': r'if\s*\([^)]*<\s*0\)',
}

# Count patterns in vulnerable vs patched code
vuln_pattern_counts = {pattern: 0 for pattern in vuln_patterns}
patch_pattern_counts = {pattern: 0 for pattern in patch_patterns}

for _, row in df_paired.iterrows():
    code = str(row['func'])
    is_vuln = row['target'] == 1
    
    if is_vuln:
        for pattern_name, regex in vuln_patterns.items():
            if re.search(regex, code, re.IGNORECASE):
                vuln_pattern_counts[pattern_name] += 1
    else:
        for pattern_name, regex in patch_patterns.items():
            if re.search(regex, code, re.IGNORECASE):
                patch_pattern_counts[pattern_name] += 1

output.write(f"### Vulnerable Code Patterns\n\n")
output.write(f"Patterns found in vulnerable functions:\n\n")
vuln_df = pd.DataFrame({
    'Pattern': list(vuln_pattern_counts.keys()),
    'Count': list(vuln_pattern_counts.values()),
    'Percentage': [f"{(v/len(df_paired[df_paired['target']==1])*100):.2f}%" for v in vuln_pattern_counts.values()]
}).sort_values('Count', ascending=False)
output.write(vuln_df.to_markdown(index=False))
output.write("\n\n")

output.write(f"### Patch/Fix Patterns\n\n")
output.write(f"Patterns found in patched functions:\n\n")
patch_df = pd.DataFrame({
    'Pattern': list(patch_pattern_counts.keys()),
    'Count': list(patch_pattern_counts.values()),
    'Percentage': [f"{(v/len(df_paired[df_paired['target']==0])*100):.2f}%" for v in patch_pattern_counts.values()]
}).sort_values('Count', ascending=False)
output.write(patch_df.to_markdown(index=False))
output.write("\n\n")

# Visualization
fig, axes = plt.subplots(1, 2, figsize=(18, 6))

# Vulnerable patterns
vuln_df.sort_values('Count').tail(10).plot(x='Pattern', y='Count', kind='barh', ax=axes[0], color='#e74c3c', legend=False)
axes[0].set_title('Top 10 Vulnerable Code Patterns')
axes[0].set_xlabel('Count')
axes[0].set_ylabel('')

# Patch patterns
patch_df.sort_values('Count').tail(10).plot(x='Pattern', y='Count', kind='barh', ax=axes[1], color='#2ecc71', legend=False)
axes[1].set_title('Top 10 Patch/Fix Patterns')
axes[1].set_xlabel('Count')
axes[1].set_ylabel('')

plt.tight_layout()
pattern_plot_path = output_dir / "train_paired" / "code_patterns.png"
plt.savefig(pattern_plot_path)
plt.close()

output.write(f"![Code Patterns]({pattern_plot_path.name})\n\n")

# Write to report
with open(report_path, "a") as f:
    f.write(output.getvalue())

print(output.getvalue())

## 6. Code Pattern Analysis

### Vulnerable Code Patterns

Patterns found in vulnerable functions:

| Pattern        |   Count | Percentage   |
|:---------------|--------:|:-------------|
| pointer_deref  |    3110 | 82.08%       |
| array_access   |    2271 | 59.94%       |
| memcpy_call    |     524 | 13.83%       |
| free_call      |     297 | 7.84%        |
| malloc_call    |     235 | 6.20%        |
| unsafe_strcpy  |      78 | 2.06%        |
| unsafe_sprintf |      57 | 1.50%        |
| unsafe_strcat  |      24 | 0.63%        |
| unsafe_gets    |       0 | 0.00%        |

### Patch/Fix Patterns

Patterns found in patched functions:

| Pattern       |   Count | Percentage   |
|:--------------|--------:|:-------------|
| size_check    |    3051 | 80.52%       |
| bounds_check  |    2119 | 55.93%       |
| return_check  |     596 | 15.73%       |
| null_check    |     302 | 7.97%        |
| safe_snprintf |     126 | 3.33%        |
| safe_strncpy  |      63 | 1.66%        |
| safe_strncat  |       6 | 0.16%        |

![Code Patterns](code_patterns.png)

## 7. Function Completeness Check

Verify if functions are complete for Coming analysis

In [35]:
# Function Completeness Check
output = StringIO()
output.write("## 7. Function Completeness Analysis\n\n")

def check_completeness(code):
    """Check if function appears complete"""
    code_str = str(code)
    
    # Check for opening and closing braces
    open_braces = code_str.count('{')
    close_braces = code_str.count('}')
    
    # Check for function signature
    has_signature = bool(re.search(r'\w+\s+\w+\s*\([^)]*\)', code_str))
    
    # Check if braces are balanced
    balanced_braces = open_braces == close_braces and open_braces > 0
    
    return {
        'has_signature': has_signature,
        'balanced_braces': balanced_braces,
        'open_braces': open_braces,
        'close_braces': close_braces,
        'complete': has_signature and balanced_braces
    }

# Analyze completeness
completeness_results = df_paired['func'].apply(check_completeness)
df_paired['is_complete'] = completeness_results.apply(lambda x: x['complete'])

complete_count = df_paired['is_complete'].sum()
incomplete_count = len(df_paired) - complete_count

output.write(f"### Completeness Statistics\n\n")
output.write(f"- **Complete functions:** {complete_count} ({complete_count/len(df_paired)*100:.2f}%)\n")
output.write(f"- **Incomplete/snippets:** {incomplete_count} ({incomplete_count/len(df_paired)*100:.2f}%)\n\n")

# Check by target
vuln_complete = df_paired[df_paired['target'] == 1]['is_complete'].sum()
patch_complete = df_paired[df_paired['target'] == 0]['is_complete'].sum()
vuln_total = len(df_paired[df_paired['target'] == 1])
patch_total = len(df_paired[df_paired['target'] == 0])

output.write(f"### Completeness by Target\n\n")
output.write(f"**Vulnerable functions:**\n")
output.write(f"- Complete: {vuln_complete}/{vuln_total} ({vuln_complete/vuln_total*100:.2f}%)\n\n")

output.write(f"**Patched functions:**\n")
output.write(f"- Complete: {patch_complete}/{patch_total} ({patch_complete/patch_total*100:.2f}%)\n\n")

# Check paired completeness
paired_complete = 0
for cve, group in df_paired.groupby('cve'):
    vuln = group[group['target'] == 1]
    patch = group[group['target'] == 0]
    if len(vuln) > 0 and len(patch) > 0:
        if vuln.iloc[0]['is_complete'] and patch.iloc[0]['is_complete']:
            paired_complete += 1

total_cves = df_paired['cve'].nunique()
output.write(f"### Paired Completeness\n\n")
output.write(f"- **CVEs with both functions complete:** {paired_complete}/{total_cves} ({paired_complete/total_cves*100:.2f}%)\n")
output.write(f"- **Suitable for Coming analysis:** {paired_complete} pairs\n\n")

if paired_complete < total_cves * 0.5:
    output.write(f"⚠️ **Warning:** Less than 50% of pairs have complete functions. May need to use file_contents/ for full context.\n\n")
else:
    output.write(f"✅ **Most pairs have complete functions, suitable for Coming analysis.**\n\n")

# Sample incomplete functions
incomplete_samples = df_paired[~df_paired['is_complete']].head(3)
if len(incomplete_samples) > 0:
    output.write(f"### Examples of Incomplete Functions\n\n")
    for idx, row in incomplete_samples.iterrows():
        output.write(f"**CVE:** {row['cve']}, **Target:** {row['target']}\n")
        func_preview = str(row['func'])[:200].replace('\n', ' ')
        output.write(f"```\n{func_preview}...\n```\n\n")

# Write to report
with open(report_path, "a") as f:
    f.write(output.getvalue())

print(output.getvalue())

/var/folders/g0/yxqzhyv91b7gnrp3xrhst1h40000gn/T/ipykernel_14888/712810758.py:53: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  for cve, group in df_paired.groupby('cve'):

## 7. Function Completeness Analysis

### Completeness Statistics

- **Complete functions:** 6144 (81.08%)
- **Incomplete/snippets:** 1434 (18.92%)

### Completeness by Target

**Vulnerable functions:**
- Complete: 3058/3789 (80.71%)

**Patched functions:**
- Complete: 3086/3789 (81.45%)

### Paired Completeness

- **CVEs with both functions complete:** 2623/3266 (80.31%)
- **Suitable for Coming analysis:** 2623 pairs

✅ **Most pairs have complete functions, suitable for Coming analysis.**

### Examples of Incomplete Functions

**CVE:** CVE-2011-4128, **Target:** 1
```
gnutls_session_get_data (gnutls_session_t session,                          void *session_data, size_t * session_data_size) {    gnutls_datum_t psession;   int ret;    if (session->internals.resumable...
```

**CVE:** CVE-2011-4128, **Target:** 0
```
gnutls_session_get_data (gnutls_session_t session,                          void *session_data, size_t * session_data_size) {    gnutls_datum_t psession;   int ret;    if (session->internals.resumable...
```

**CVE:** CVE-2011-4128, **Target:** 1
```
gnutls_session_get_data (gnutls_session_t session,                          void *session_data, size_t * session_data_size) {    gnutls_datum_t psession;   int ret;    if (session->internals.resumable...
```

## 8. Research Recommendations

Generate actionable insights for research planning

In [36]:
# Generate Research Recommendations
output = StringIO()
output.write("## 8. Research Recommendations\n\n")

output.write("Based on the comprehensive analysis above, here are actionable recommendations for your vulnerability research:\n\n")

output.write("### 🎯 Priority Research Directions\n\n")

# Identify dominant CWE categories
if 'primary_cwe' in df_paired.columns:
    top_3_cwes = df_paired['primary_cwe'].value_counts().head(3)
    output.write("#### 1. Focus on High-Impact CWE Categories\n\n")
    output.write(f"The dataset is dominated by these vulnerability types:\n\n")
    for i, (cwe, count) in enumerate(top_3_cwes.items(), 1):
        output.write(f"{i}. **{cwe}**: {count} samples - Start Coming analysis here\n")
    output.write("\n")

output.write("#### 2. Project-Specific Analysis\n\n")
output.write(f"Major projects like **Linux kernel**, **ImageMagick**, and **Chromium** have sufficient samples (>100) for statistical significance. Consider:\n")
output.write(f"- Building project-specific vulnerability profiles\n")
output.write(f"- Comparing fix patterns across projects for same CWE\n")
output.write(f"- Identifying project-specific coding practices that reduce vulnerabilities\n\n")

output.write("#### 3. Code Change Pattern Mining\n\n")
if paired_complete > 100:
    output.write(f"With **{paired_complete} complete function pairs**, you can:\n")
    output.write(f"- Use Coming to extract AST-level change patterns\n")
    output.write(f"- Build a taxonomy of security fix types\n")
    output.write(f"- Train ML models to predict fix strategies\n\n")
else:
    output.write(f"⚠️ Only {paired_complete} complete pairs available. Consider using `file_contents/` directory for full context.\n\n")

output.write("### 🛠️ Coming Tool Strategy\n\n")

output.write("#### Recommended Pipeline:\n\n")
output.write("1. **Pilot Study (Week 1-2)**\n")
output.write(f"   - Select {min(100, paired_complete)} samples from CWE-119 (buffer overflow)\n")
output.write(f"   - Convert to Coming format (`diff_N/func_s.c` and `func_t.c`)\n")
output.write(f"   - Run pattern mining: `coming -mode mineinstance -action INS -entitytype BinaryOperator`\n")
output.write(f"   - Validate that Coming produces meaningful patterns\n\n")

output.write("2. **Scaling Up (Week 3-4)**\n")
output.write(f"   - Process all {paired_complete} complete pairs\n")
output.write(f"   - Extract features using `coming -mode features`\n")
output.write(f"   - Build CWE-specific pattern libraries\n\n")

output.write("3. **Analysis & Modeling (Week 5+)**\n")
output.write(f"   - Cluster similar fix patterns\n")
output.write(f"   - Build predictive models (vulnerability type → expected fix pattern)\n")
output.write(f"   - Cross-validate on test set\n\n")

output.write("### 📊 Predictive Modeling Opportunities\n\n")

output.write("#### Research Questions You Can Answer:\n\n")
output.write("1. **Pattern Discovery**\n")
output.write(f"   - What are the 10 most common AST change patterns in security fixes?\n")
output.write(f"   - Do different CWE categories have distinct fix signatures?\n\n")

output.write("2. **Vulnerability Prediction**\n")
output.write(f"   - Can code features predict vulnerability type (CWE classification)?\n")
output.write(f"   - Which code metrics correlate with vulnerability severity?\n\n")

output.write("3. **Fix Quality Analysis**\n")
output.write(f"   - Do minimal fixes (few LOC changes) differ in effectiveness from refactorings?\n")
output.write(f"   - What's the relationship between fix complexity and vulnerability recurrence?\n\n")

output.write("4. **Causal Inference**\n")
output.write(f"   - Do bounds checks **causally** reduce buffer overflows? (use propensity score matching)\n")
output.write(f"   - What code change patterns **cause** vulnerabilities vs fix them?\n\n")

output.write("### ⚠️ Data Quality Considerations\n\n")

# Check for issues
issues = []
if incomplete_count > total_samples * 0.3:
    issues.append(f"- {incomplete_count} incomplete functions ({incomplete_count/len(df_paired)*100:.1f}%) - may need full file context")

if cves_only_vuln > 0 or cves_only_patch > 0:
    issues.append(f"- {cves_only_vuln + cves_only_patch} CVEs with unpaired data - exclude from paired analysis")

if len(df_paired[df_paired['file_hash'].isna()]) > 0:
    issues.append(f"- {len(df_paired[df_paired['file_hash'].isna()])} samples missing file_hash - cannot retrieve full context")

if issues:
    output.write("**Known issues to address:**\n\n")
    for issue in issues:
        output.write(f"{issue}\n")
    output.write("\n")
else:
    output.write("✅ **No major data quality issues identified**\n\n")

output.write("### 🚀 Next Steps\n\n")

output.write("**Immediate (This Week):**\n")
output.write("1. Create `src/primevul_analysis/converter.py` to convert PrimeVul → Coming format\n")
output.write(f"2. Select pilot subset: {min(100, paired_complete)} CWE-119 pairs\n")
output.write("3. Test Coming integration with pilot data\n\n")

output.write("**Short-term (Next 2 Weeks):**\n")
output.write("4. Process full dataset through Coming\n")
output.write("5. Build pattern frequency database\n")
output.write("6. Create visualization dashboard (Jupyter widgets or Streamlit)\n\n")

output.write("**Medium-term (Month 2):**\n")
output.write("7. Extract ML features from Coming output\n")
output.write("8. Train baseline classifiers (RandomForest, XGBoost)\n")
output.write("9. Implement causal inference pipeline\n")
output.write("10. Write preliminary findings report\n\n")

output.write("---\n\n")
output.write(f"*Analysis complete. Report generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n")

# Write to report
with open(report_path, "a") as f:
    f.write(output.getvalue())

print(output.getvalue())
print(f"\n✅ Full report saved to: {report_path}")

## 8. Research Recommendations

Based on the comprehensive analysis above, here are actionable recommendations for your vulnerability research:

### 🎯 Priority Research Directions

#### 1. Focus on High-Impact CWE Categories

The dataset is dominated by these vulnerability types:

1. **CWE-119**: 1041 samples - Start Coming analysis here
2. **CWE-125**: 790 samples - Start Coming analysis here
3. **CWE-20**: 697 samples - Start Coming analysis here

#### 2. Project-Specific Analysis

Major projects like **Linux kernel**, **ImageMagick**, and **Chromium** have sufficient samples (>100) for statistical significance. Consider:
- Building project-specific vulnerability profiles
- Comparing fix patterns across projects for same CWE
- Identifying project-specific coding practices that reduce vulnerabilities

#### 3. Code Change Pattern Mining

With **2623 complete function pairs**, you can:
- Use Coming to extract AST-level change patterns
- Build a taxonomy of security fix types
- Train ML models to predict fix strategies

### 🛠️ Coming Tool Strategy

#### Recommended Pipeline:

1. **Pilot Study (Week 1-2)**
   - Select 100 samples from CWE-119 (buffer overflow)
   - Convert to Coming format (`diff_N/func_s.c` and `func_t.c`)
   - Run pattern mining: `coming -mode mineinstance -action INS -entitytype BinaryOperator`
   - Validate that Coming produces meaningful patterns

2. **Scaling Up (Week 3-4)**
   - Process all 2623 complete pairs
   - Extract features using `coming -mode features`
   - Build CWE-specific pattern libraries

3. **Analysis & Modeling (Week 5+)**
   - Cluster similar fix patterns
   - Build predictive models (vulnerability type → expected fix pattern)
   - Cross-validate on test set

### 📊 Predictive Modeling Opportunities

#### Research Questions You Can Answer:

1. **Pattern Discovery**
   - What are the 10 most common AST change patterns in security fixes?
   - Do different CWE categories have distinct fix signatures?

2. **Vulnerability Prediction**
   - Can code features predict vulnerability type (CWE classification)?
   - Which code metrics correlate with vulnerability severity?

3. **Fix Quality Analysis**
   - Do minimal fixes (few LOC changes) differ in effectiveness from refactorings?
   - What's the relationship between fix complexity and vulnerability recurrence?

4. **Causal Inference**
   - Do bounds checks **causally** reduce buffer overflows? (use propensity score matching)
   - What code change patterns **cause** vulnerabilities vs fix them?

### ⚠️ Data Quality Considerations

**Known issues to address:**

- 10 CVEs with unpaired data - exclude from paired analysis
- 2705 samples missing file_hash - cannot retrieve full context

### 🚀 Next Steps

**Immediate (This Week):**
1. Create `src/primevul_analysis/converter.py` to convert PrimeVul → Coming format
2. Select pilot subset: 100 CWE-119 pairs
3. Test Coming integration with pilot data

**Short-term (Next 2 Weeks):**
4. Process full dataset through Coming
5. Build pattern frequency database
6. Create visualization dashboard (Jupyter widgets or Streamlit)

**Medium-term (Month 2):**
7. Extract ML features from Coming output
8. Train baseline classifiers (RandomForest, XGBoost)
9. Implement causal inference pipeline
10. Write preliminary findings report

---

*Analysis complete. Report generated on 2025-12-18 15:37:50*


✅ Full report saved to: results/train_paired/llm_generated_report.md

## Summary

Run all cells in this section to generate a comprehensive analysis report at:
`notebooks/results/train_paired/llm_generated_report.md`

The analysis includes:
1. Target distribution (vulnerable vs patched balance)
2. Pairing validation (checking data quality)
3. CWE distribution (vulnerability types)
4. Code length analysis (LOC changes in fixes)
5. CWE by project (project-specific patterns)
6. Code pattern mining (unsafe functions, safety checks)
7. Function completeness (suitability for Coming)
8. Research recommendations (actionable next steps)